package io.github.aasaru.drools.section03.step1
 
import io.github.aasaru.drools.domain.Passport;
import java.time.LocalDate;

rule "Valid passport"
  dialect "mvel"
  when
	Passport( !isExpired(), $unsedPages : unusedVisaPages > 0, $name : name )
  then
	System.out.printf("This passport of %s is CORRECT, it has %d unused pages \n", $name , $unsedPages);
end

rule "Expired or full passport"
  dialect "java"
  when
	Passport( isExpired() || unusedVisaPages == 0 )
  then
	System.out.println( "This passport is INVALID because it is expired or has no space for visa" );
end


rule "Valid passport but not many pages left"
  dialect "mvel"
  when
  $passport : Passport( !isExpired() , unusedVisaPagesBetween(0,11))
  then
  System.out.printf("The passport of %s is VALID but has only %s pages left \n", $passport.name, $passport.unusedVisaPages)
end 